sonar.projectKey=EthanCharlier_atm-sim
sonar.organization=ethancharlier
sonar.projectName=ATM Simulation
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.14
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/.venv/**,**/data/**

sonar.python.ruff.reportPaths=ruff-report.json